# default values
ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
FLIP_OPTIONS = ["None", "X", "Y", "Both"]
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ["None", "Emboss", "Find edges", "Contour", "Edge enhance"]
CRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GRAYSCALE_DEFAULT = False
INVERT_DEFAULT = False

# Colors
BACKGROUND_COLOR = "#525252"
WHITE = "#ffffff"
GREY = "#808080"
BLUE = "#1f6aa5"
DARK_GREY = "#696969"
CLOSE_RED = "#8a0606"
SLIDER_BG = "#64686b"